// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgjvtahdvtlwkogjqjyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnanZ0YWhkdnRsd2tvZ2pxanluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NzUwNzYsImV4cCI6MjA0OTU1MTA3Nn0.XFfindPHAMSBwekIkhs8yzGH2XHr2AIWzWr80NrEy60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);